/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cStopPow;

public class StopPow_AZ extends StopPow {
  private transient long swigCPtr;

  protected StopPow_AZ(long cPtr, boolean cMemoryOwn) {
    super(cStopPowJNI.StopPow_AZ_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StopPow_AZ obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cStopPowJNI.delete_StopPow_AZ(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public StopPow_AZ(int Z) throws IllegalArgumentException {
    this(cStopPowJNI.new_StopPow_AZ__SWIG_0(Z), true);
  }

  public StopPow_AZ(int Z, double rho) throws IllegalArgumentException {
    this(cStopPowJNI.new_StopPow_AZ__SWIG_1(Z, rho), true);
  }

  public double dEdx_MeV_um(double E) throws IllegalArgumentException {
    return cStopPowJNI.StopPow_AZ_dEdx_MeV_um(swigCPtr, this, E);
  }

  public double dEdx_MeV_mgcm2(double E) throws IllegalArgumentException {
    return cStopPowJNI.StopPow_AZ_dEdx_MeV_mgcm2(swigCPtr, this, E);
  }

  public double get_Emin() {
    return cStopPowJNI.StopPow_AZ_get_Emin(swigCPtr, this);
  }

  public double get_Emax() {
    return cStopPowJNI.StopPow_AZ_get_Emax(swigCPtr, this);
  }

}
