/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cStopPow;

public class StopPow {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StopPow(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StopPow obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cStopPowJNI.delete_StopPow(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public double dEdx_MeV_um(double E) {
    return cStopPowJNI.StopPow_dEdx_MeV_um(swigCPtr, this, E);
  }

  public double dEdx_MeV_mgcm2(double E) {
    return cStopPowJNI.StopPow_dEdx_MeV_mgcm2(swigCPtr, this, E);
  }

  public double get_Emin() {
    return cStopPowJNI.StopPow_get_Emin(swigCPtr, this);
  }

  public double get_Emax() {
    return cStopPowJNI.StopPow_get_Emax(swigCPtr, this);
  }

  public String get_type() {
    return cStopPowJNI.StopPow_get_type(swigCPtr, this);
  }

  public String get_info() {
    return cStopPowJNI.StopPow_get_info(swigCPtr, this);
  }

  public double dEdx(double E) throws IllegalArgumentException {
    return cStopPowJNI.StopPow_dEdx(swigCPtr, this, E);
  }

  public double Eout(double E, double x) throws IllegalArgumentException {
    return cStopPowJNI.StopPow_Eout(swigCPtr, this, E, x);
  }

  public double Ein(double E, double x) throws IllegalArgumentException {
    return cStopPowJNI.StopPow_Ein(swigCPtr, this, E, x);
  }

  public double Thickness(double E1, double E2) throws IllegalArgumentException {
    return cStopPowJNI.StopPow_Thickness(swigCPtr, this, E1, E2);
  }

  public double Range(double E) throws IllegalArgumentException {
    return cStopPowJNI.StopPow_Range(swigCPtr, this, E);
  }

  public int get_mode() {
    return cStopPowJNI.StopPow_get_mode(swigCPtr, this);
  }

  public void set_mode(int new_mode) throws IllegalArgumentException {
    cStopPowJNI.StopPow_set_mode(swigCPtr, this, new_mode);
  }

  public static int getMODE_LENGTH() {
    return cStopPowJNI.StopPow_MODE_LENGTH_get();
  }

  public static int getMODE_RHOR() {
    return cStopPowJNI.StopPow_MODE_RHOR_get();
  }

}
