/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cStopPow;

public class StopPow_BetheBloch extends StopPow {
  private transient long swigCPtr;

  protected StopPow_BetheBloch(long cPtr, boolean cMemoryOwn) {
    super(cStopPowJNI.StopPow_BetheBloch_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StopPow_BetheBloch obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cStopPowJNI.delete_StopPow_BetheBloch(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public StopPow_BetheBloch(double mt, double Zt, DoubleVector mf, DoubleVector Zf, DoubleVector nf) throws IllegalArgumentException {
    this(cStopPowJNI.new_StopPow_BetheBloch(mt, Zt, DoubleVector.getCPtr(mf), mf, DoubleVector.getCPtr(Zf), Zf, DoubleVector.getCPtr(nf), nf), true);
  }

  public double dEdx_MeV_um(double E) throws IllegalArgumentException {
    return cStopPowJNI.StopPow_BetheBloch_dEdx_MeV_um(swigCPtr, this, E);
  }

  public double dEdx_MeV_mgcm2(double E) throws IllegalArgumentException {
    return cStopPowJNI.StopPow_BetheBloch_dEdx_MeV_mgcm2(swigCPtr, this, E);
  }

  public double get_Emin() {
    return cStopPowJNI.StopPow_BetheBloch_get_Emin(swigCPtr, this);
  }

  public double get_Emax() {
    return cStopPowJNI.StopPow_BetheBloch_get_Emax(swigCPtr, this);
  }

  public void use_shell_correction(boolean enabled) {
    cStopPowJNI.StopPow_BetheBloch_use_shell_correction(swigCPtr, this, enabled);
  }

  public boolean using_shell_correction() {
    return cStopPowJNI.StopPow_BetheBloch_using_shell_correction(swigCPtr, this);
  }

  public void set_Ibar(DoubleVector Ibar) throws IllegalArgumentException {
    cStopPowJNI.StopPow_BetheBloch_set_Ibar(swigCPtr, this, DoubleVector.getCPtr(Ibar), Ibar);
  }

  public double Ibar(double Zf) {
    return cStopPowJNI.StopPow_BetheBloch_Ibar(swigCPtr, this, Zf);
  }

}
