/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cStopPow;

public class StopPow_SRIM extends StopPow {
  private transient long swigCPtr;

  protected StopPow_SRIM(long cPtr, boolean cMemoryOwn) {
    super(cStopPowJNI.StopPow_SRIM_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StopPow_SRIM obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cStopPowJNI.delete_StopPow_SRIM(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public StopPow_SRIM(String fname) throws java.io.IOException {
    this(cStopPowJNI.new_StopPow_SRIM(fname), true);
  }

  public double dEdx_MeV_um(double E) throws IllegalArgumentException {
    return cStopPowJNI.StopPow_SRIM_dEdx_MeV_um(swigCPtr, this, E);
  }

  public double dEdx_MeV_mgcm2(double E) throws IllegalArgumentException {
    return cStopPowJNI.StopPow_SRIM_dEdx_MeV_mgcm2(swigCPtr, this, E);
  }

  public double get_Emin() {
    return cStopPowJNI.StopPow_SRIM_get_Emin(swigCPtr, this);
  }

  public double get_Emax() {
    return cStopPowJNI.StopPow_SRIM_get_Emax(swigCPtr, this);
  }

}
