/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cStopPow;

public class StopPow_Fit extends StopPow_PartialIoniz {
  private transient long swigCPtr;

  protected StopPow_Fit(long cPtr, boolean cMemoryOwn) {
    super(cStopPowJNI.StopPow_Fit_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StopPow_Fit obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cStopPowJNI.delete_StopPow_Fit(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public StopPow_Fit(double mt, double Zt, DoubleVector mf, DoubleVector Zf, DoubleVector Tf, DoubleVector nf, DoubleVector Zbar, double Te) throws IllegalArgumentException {
    this(cStopPowJNI.new_StopPow_Fit__SWIG_0(mt, Zt, DoubleVector.getCPtr(mf), mf, DoubleVector.getCPtr(Zf), Zf, DoubleVector.getCPtr(Tf), Tf, DoubleVector.getCPtr(nf), nf, DoubleVector.getCPtr(Zbar), Zbar, Te), true);
  }

  public StopPow_Fit(double mt, double Zt, SWIGTYPE_p_std__vectorT_std__arrayT_double_5_t_t field, double Te) throws IllegalArgumentException {
    this(cStopPowJNI.new_StopPow_Fit__SWIG_1(mt, Zt, SWIGTYPE_p_std__vectorT_std__arrayT_double_5_t_t.getCPtr(field), Te), true);
  }

  public double dEdx_MeV_um(double E) throws IllegalArgumentException {
    return cStopPowJNI.StopPow_Fit_dEdx_MeV_um(swigCPtr, this, E);
  }

  public double dEdx_MeV_mgcm2(double E) throws IllegalArgumentException {
    return cStopPowJNI.StopPow_Fit_dEdx_MeV_mgcm2(swigCPtr, this, E);
  }

  public double get_Emin() {
    return cStopPowJNI.StopPow_Fit_get_Emin(swigCPtr, this);
  }

  public double get_Emax() {
    return cStopPowJNI.StopPow_Fit_get_Emax(swigCPtr, this);
  }

  public void normalize_bound_e(StopPow ref, double Ep) {
    cStopPowJNI.StopPow_Fit_normalize_bound_e(swigCPtr, this, StopPow.getCPtr(ref), ref, Ep);
  }

  public static int getMODE_ZIMMERMAN() {
    return cStopPowJNI.StopPow_Fit_MODE_ZIMMERMAN_get();
  }

  public static int getMODE_LP() {
    return cStopPowJNI.StopPow_Fit_MODE_LP_get();
  }

  public static int getMODE_LP_PUB() {
    return cStopPowJNI.StopPow_Fit_MODE_LP_PUB_get();
  }

  public static int getMODE_BPS() {
    return cStopPowJNI.StopPow_Fit_MODE_BPS_get();
  }

  public static int getMODE_GRABOWSKI() {
    return cStopPowJNI.StopPow_Fit_MODE_GRABOWSKI_get();
  }

  public static int getMODE_QUANTUM_GRABOWSKI() {
    return cStopPowJNI.StopPow_Fit_MODE_QUANTUM_GRABOWSKI_get();
  }

  public void choose_model(int new_model) throws IllegalArgumentException {
    cStopPowJNI.StopPow_Fit_choose_model(swigCPtr, this, new_model);
  }

  public void set_factor(double factor) {
    cStopPowJNI.StopPow_Fit_set_factor(swigCPtr, this, factor);
  }

  public double get_factor() {
    return cStopPowJNI.StopPow_Fit_get_factor(swigCPtr, this);
  }

}
